resources:
 pipelines:
   - pipeline: Test2
     source: Arsasana.Test2
 containers:
    - container: ACRResourceLatest2
      type: ACR
      azureSubscription: ARM_Connection
      resourceGroup: RMINT
      registry: ansheno
      repository: containerrepo
stages:
 - stage: ConsumedContainer
   jobs:
    - job: download_specific_artifact1
      displayName: download specific artifact1
      pool:
        name: Default
    - job: J9
      pool: 
       name: Default
      steps:
        - download: Test2

 - stage: ProduceAndConsumePipelineArtifact
   jobs:
    - job: J1
      pool:
       name: Default
      steps:
       - task: PublishBuildArtifacts@1
         inputs:
          PathtoPublish: 'artifact3'
          ArtifactName: 'A3'
    - job: J8
      pool: 
       name: Default
      steps:
        - download: Test2
    - job: J10
      pool: 
       name: Default
      steps:
        - download: Test2
    - job: download_specific_artifact1
      displayName: download specific artifact1
      pool:
        name: Default