resources:
 pipelines:
   - pipeline: CIPipeline
     source: Arsasana.Test2
     tags: test
#  containers:
#     - container: ACRResource
#       type: ACR
#       azureSubscription: azrm
#       resourceGroup: ansheno
#       registry: ansheno
#       repository: ansheno
#       trigger: true

    # - container: ACRResourceLatest2
    #   type: ACR
    #   azureSubscription: ARM_Automatic
    #   resourceGroup: RMINT
    #   registry: ansheno
    #   repository: containerrepo
stages:
#  - stage: ConsumedContainer
#    jobs:
#     - job: download_specific_artifact1
#       displayName: download specific artifact1
#       pool:
#         vmImage: 'ubuntu-latest'
#     - job: J9
#       pool: 
#        vmImage: 'ubuntu-latest'
#       steps:
#         - download: Test2

 - stage: ProduceAndConsumePipelineArtifact
   jobs:
    # - job: J1
    #   pool:
    #     name : 'Default'
    #   #  vmImage: 'ubuntu-latest'
    #   steps:
    #    - task: PublishBuildArtifacts@1
    #      inputs:
    #       PathtoPublish: 'artifact3'
    #       ArtifactName: 'A3'
    - job: Job8
      pool: 
        name : 'Default'
      #  vmImage: 'ubuntu-latest'
      steps:
        - download: CIPipeline
    # - job: J10
    #   pool: 
    #    vmImage: 'ubuntu-latest'
    #   steps:
    #     - download: Test2
    # - job: download_specific_artifact1
    #   displayName: download specific artifact1
    #   pool:
    #     vmImage: 'ubuntu-latest'