resources:
 pipelines:
   - pipeline: Test2
     source: oct23
     project: oct23

trigger:
- master

stages:
 - stage: ProduceArtifact
   jobs:
     - job: J8
       pool: 
        name: Default
       steps:
         - download: Test2
          #  artifact: A1.1
         - task: PublishBuildArtifacts@1
           inputs:
            PathtoPublish: 'artifact3'
            ArtifactName: 'A3_Project2'
            publishLocation: 'Container'
        #  - powershell: |
        #     ls $(Build.ArtifactStagingDirectory)/
