resources:
 containers:
  - container: ACRResourceLatest2
    type: ACR
    azureSubscription: ARM_Connection
    resourceGroup: RMINT
    registry: ansheno
    repository: containerrepo
 pipelines:
   - pipeline: CIPipeline
     source: Arsasana.Test2


trigger: none

stages:
 - stage: ProduceArtifact
   jobs:
     - job: J4
       pool: 
        name: Default
       steps:
         - download: CIPipeline
          #  artifact: A1.1
         - task: PublishBuildArtifacts@1
           inputs:
            PathtoPublish: 'artifact3'
            ArtifactName: 'A3_Project2'
            publishLocation: 'Container'
        #  - powershell: |
        #     ls $(Build.ArtifactStagingDirectory)/
